### ISSUE TITLE
Vue config needs VueLoaderPlugin

### ISSUE THREAD

**Issue by lewisvatcky** [DeloitteDigitalAPAC/webpack-config#27]
https://vue-loader.vuejs.org/guide/#manual-configuration

The `VueLoaderPlugin` is required as part of the default config. I had a go at using this config in a project and I couldn't add `sass-loader` because the plugin was missing.

**Comment by keeganstreet** [comment]
Hey Lewis, we're currently running Vue Loader v14, which does not require the plugin. Renovate has opened an automated PR from the branch "renovate/vue-loader-15.x" to upgrade to Vue Loader v15, but I haven't merged this PR because the demo project doesn't build any more on this branch. Would you like to take a look at the migration steps from v14 to v15, which would include adding the plugin?

**Comment by lewisvatcky** [comment]
Hey Keegan, makes sense to me. I'll take a look and make sure we're not breaking anything by migrating.

**Comment by keeganstreet** [comment]
Fixed by https://github.com/DeloitteDigitalAPAC/webpack-config/pull/11/
