### ISSUE TITLE
Defaulting css-loader url to false can be miss leading

### ISSUE THREAD

**Issue by jennasalau** [DeloitteDigitalAPAC/webpack-config#79]
Related to #26 

I have been pulling my hair out trying to figure out why fonts where not loading.

We have defaulted our css-loader url option to `false`.

https://github.com/DeloitteDigitalAPAC/webpack-config/blob/master/packages/webpack-config/src/index.js#L101

Where as the library normally has it as `true`.

https://github.com/webpack-contrib/css-loader#url

Because in our projects we are using file-loader it means none of the assets referenced in scss are ever included in the build.

I think we need to either add clear documentation to override when using file loader or turn it back to  a default of true.

**Comment by dkeeghan** [comment]
Agreed it's a good point. What was the rational for having it set to false?

**Comment by keeganstreet** [comment]
Hey, I agree Jenna, also overrode this on my most recent project and add file loader. I would suggest we set to true and add file loader at the same time. Otherwise we will create massive CSS files with fonts embedded inside them.
DK is Michael D on the bench this week? If so he could bring across our file loader settings from Digital Heartbeat.
